[project]
name = "torun-bo-mapa"
version = "0.1.0"
description = "Map visualization of the budżet obywatelski of the city of Toruń, Poland."
requires-python = ">=3"
dependencies = [
    "mypy",
    "pdfplumber",
]
