name: test

on:
  pull_request:
  push:
    branches:
      - main
  # Run on first day of month at 3 AM UTC
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: astral.sh/uv/install.sh
        run: |
          set -eo pipefail
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: uv sync
        run: |
          set -eo pipefail
          uv sync

      - name: data/2025.raw.json
        run: |
          set -eo pipefail
          uv run --frozen python preprocessing/extract_bo_2025.py > 2025.raw.json
          diff data/2025.raw.json 2025.raw.json

      - name: data/2024.raw.json
        run: |
          set -eo pipefail
          uv run --frozen python preprocessing/extract_bo_2024.py > 2024.raw.json
          diff data/2024.raw.json 2024.raw.json

      - name: uv run --frozen python -m mypy preprocessing
        run: |
          set -eo pipefail
          uv run --frozen python -m mypy preprocessing
